In [1]:
import pandas as pd
import numpy as np

In [2]:
car = pd.read_csv('quikr_car.csv')

In [3]:
car

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel
...,...,...,...,...,...,...
887,Ta,Tara,zest,"3,10,000",NaN,NaN
888,Tata Zest XM Diesel,Tata,2018,"2,60,000","27,000 kms",Diesel
889,Mahindra Quanto C8,Mahindra,2013,"3,90,000","40,000 kms",Diesel
890,Honda Amaze 1.2 E i VTEC,Honda,2014,"1,80,000",Petrol,NaN
891,Chevrolet Sail 1.2 LT ABS,Chevrolet,2014,"1,60,000",Petrol,NaN

In [4]:
car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 892 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        892 non-null    object
 1   company     892 non-null    object
 2   year        892 non-null    object
 3   Price       892 non-null    object
 4   kms_driven  840 non-null    object
 5   fuel_type   837 non-null    object
dtypes: object(6)
memory usage: 41.9+ KB

In [5]:
car['year'].unique()

array(['2007', '2006', '2018', '2014', '2015', '2012', '2013', '2016',
       '2010', '2017', '2008', '2011', '2019', '2009', '2005', '2000',
       '...', '150k', 'TOUR', '2003', 'r 15', '2004', 'Zest', '/-Rs',
       'sale', '1995', 'ara)', '2002', 'SELL', '2001', 'tion', 'odel',
       '2 bs', 'arry', 'Eon', 'o...', 'ture', 'emi', 'car', 'able', 'no.',
       'd...', 'SALE', 'digo', 'sell', 'd Ex', 'n...', 'e...', 'D...',
       ', Ac', 'go .', 'k...', 'o c4', 'zire', 'cent', 'Sumo', 'cab',
       't xe', 'EV2', 'r...', 'zest'], dtype=object)

## cleaning the data

In [6]:
backup=car.copy()

## year has many non-year values

In [7]:
car=car[car['year'].str.isnumeric()]

## convert it into integer

In [8]:
car['year']=car['year'].astype(int)

<ipython-input-8-c95edc1f455b>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  car['year']=car['year'].astype(int)

In [9]:
car.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 842 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        842 non-null    object
 1   company     842 non-null    object
 2   year        842 non-null    int32
 3   Price       842 non-null    object
 4   kms_driven  840 non-null    object
 5   fuel_type   837 non-null    object
dtypes: int32(1), object(5)
memory usage: 42.8+ KB

## dont include value if it is not a price

In [10]:
car=car[car['Price']!='Ask For Price']

## convert it into interger

In [11]:
car['Price']=car['Price'].str.replace(',','').astype(int)

In [12]:
car.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 819 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        819 non-null    object
 1   company     819 non-null    object
 2   year        819 non-null    int32
 3   Price       819 non-null    int32
 4   kms_driven  819 non-null    object
 5   fuel_type   816 non-null    object
dtypes: int32(2), object(4)
memory usage: 38.4+ KB

In [13]:
car['kms_driven']=car['kms_driven'].str.split().str.get(0).str.replace(',','')

## It has nan values and two rows petrol in them

In [14]:
car=car[car['kms_driven'].str.isnumeric()]

In [15]:
car['kms_driven']=car['kms_driven'].astype(int)

In [16]:
car.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 817 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        817 non-null    object
 1   company     817 non-null    object
 2   year        817 non-null    int32
 3   Price       817 non-null    int32
 4   kms_driven  817 non-null    int32
 5   fuel_type   816 non-null    object
dtypes: int32(3), object(3)
memory usage: 35.1+ KB

## fuel type has nan values

In [17]:
car=car[~car['fuel_type'].isna()]

In [18]:
car['name'] = car['name'].str.split(' ').str.slice(0,3).str.join(' ')

In [19]:
car.head()

                     name   company  year   Price  kms_driven fuel_type
0     Hyundai Santro Xing   Hyundai  2007   80000       45000    Petrol
1     Mahindra Jeep CL550  Mahindra  2006  425000          40    Diesel
3       Hyundai Grand i10   Hyundai  2014  325000       28000    Petrol
4  Ford EcoSport Titanium      Ford  2014  575000       36000    Diesel
6               Ford Figo      Ford  2012  175000       41000    Diesel

In [20]:
car = car.reset_index(drop = True)

## cleaned data

In [21]:
car

                       name   company  year   Price  kms_driven fuel_type
0       Hyundai Santro Xing   Hyundai  2007   80000       45000    Petrol
1       Mahindra Jeep CL550  Mahindra  2006  425000          40    Diesel
2         Hyundai Grand i10   Hyundai  2014  325000       28000    Petrol
3    Ford EcoSport Titanium      Ford  2014  575000       36000    Diesel
4                 Ford Figo      Ford  2012  175000       41000    Diesel
..                      ...       ...   ...     ...         ...       ...
811      Maruti Suzuki Ritz    Maruti  2011  270000       50000    Petrol
812          Tata Indica V2      Tata  2009  110000       30000    Diesel
813    Toyota Corolla Altis    Toyota  2009  300000      132000    Petrol
814            Tata Zest XM      Tata  2018  260000       27000    Diesel
815      Mahindra Quanto C8  Mahindra  2013  390000       40000    Diesel

[816 rows x 6 columns]

In [22]:
car.describe()

              year         Price     kms_driven
count   816.000000  8.160000e+02     816.000000
mean   2012.444853  4.117176e+05   46275.531863
std       4.002992  4.751844e+05   34297.428044
min    1995.000000  3.000000e+04       0.000000
25%    2010.000000  1.750000e+05   27000.000000
50%    2013.000000  2.999990e+05   41000.000000
75%    2015.000000  4.912500e+05   56818.500000
max    2019.000000  8.500003e+06  400000.000000

In [23]:
car = car[car['Price']<6e6].reset_index(drop = True)

In [24]:
car

                       name   company  year   Price  kms_driven fuel_type
0       Hyundai Santro Xing   Hyundai  2007   80000       45000    Petrol
1       Mahindra Jeep CL550  Mahindra  2006  425000          40    Diesel
2         Hyundai Grand i10   Hyundai  2014  325000       28000    Petrol
3    Ford EcoSport Titanium      Ford  2014  575000       36000    Diesel
4                 Ford Figo      Ford  2012  175000       41000    Diesel
..                      ...       ...   ...     ...         ...       ...
810      Maruti Suzuki Ritz    Maruti  2011  270000       50000    Petrol
811          Tata Indica V2      Tata  2009  110000       30000    Diesel
812    Toyota Corolla Altis    Toyota  2009  300000      132000    Petrol
813            Tata Zest XM      Tata  2018  260000       27000    Diesel
814      Mahindra Quanto C8  Mahindra  2013  390000       40000    Diesel

[815 rows x 6 columns]

## Model

In [25]:
car.to_csv('cleaned_car_data.csv')

In [26]:
x = car.drop(columns='Price')
y = car['Price']

In [27]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

In [28]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline

In [29]:
ohe = OneHotEncoder()
ohe.fit(x[['name','company','fuel_type']])

OneHotEncoder()

In [30]:
column_trans=make_column_transformer((OneHotEncoder(categories=ohe.categories_),['name','company','fuel_type']),
                                    remainder='passthrough')

## linear-regression model

In [31]:
lr = LinearRegression()

## making a pipe line

In [32]:
pipe=make_pipeline(column_trans,lr)

In [33]:
pipe.fit(x_train,y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories=[array(['Audi A3 Cabriolet', 'Audi A4 1.8', 'Audi A4 2.0', 'Audi A6 2.0',
       'Audi A8', 'Audi Q3 2.0', 'Audi Q5 2.0', 'Audi Q7', 'BMW 3 Series',
       'BMW 5 Series', 'BMW 7 Series', 'BMW X1', 'BMW X1 sDrive20d',
       'BMW X1 xDrive20d', 'Chevrolet Beat', 'Chevrolet Beat...
                                                                            array(['Audi', 'BMW', 'Chevrolet', 'Datsun', 'Fiat', 'Force', 'Ford',
       'Hindustan', 'Honda', 'Hyundai', 'Jaguar', 'Jeep', 'Land',
       'Mahindra', 'Maruti', 'Mercedes', 'Mini', 'Mitsubishi', 'Nissan',
       'Renault', 'Skoda', 'Tata', 'Toyota', 'Volkswagen', 'Volvo'],
      dtype=object),
                                                                            array(['Diesel', 'LPG', 'Petrol'], dtype=object)]),
                                                  ['name', 'company',
                                                   'fuel_type'])])),
                ('linearregression', LinearRegression())])

In [34]:
y_pred = pipe.predict(x_test)

In [35]:
y_pred

array([ -34329.26213308,  423603.72106717,  129088.46474505,
        628498.23090717,  302103.96945191,  373948.63599709,
        138653.6632551 ,  321514.78036091,  307147.46032004,
         88144.05200367,  584410.20748672,  434770.80530617,
        276458.50183483,  674460.76585722,  519505.38590253,
       1141541.47983722,  116844.41445113,   20449.85615489,
        219454.56997892,  292207.37853222,  180722.37533638,
        515147.04634448,  341809.13468549,  353359.73615623,
         77790.21683726,  768983.37236284,  419163.84539765,
        156448.87491552,  196964.15274114,  283212.86619783,
       1892026.16322894,  451637.81844777,  376536.42421971,
        239438.21049297,  234622.89557975,  272690.06465156,
        561395.60665409,  -73534.21297623,  333667.49208263,
         46790.69836312,  174121.93905573,  250693.44233251,
        469861.53692244,  491303.75066257,  304517.16693567,
        692127.25829715,  138004.92065203,  366940.26797786,
         54536.27219599,  603121.75728569,  450107.6151377 ,
        290423.31393205,  135813.51264255,  556914.35213708,
        809647.5081024 ,  284905.72326434,  142021.53370886,
        156620.32383157,  256112.35266439,  302842.15299508,
        236327.68507956,  366007.54112594,  521168.98439171,
        -34547.30194172,  157141.11424151,  601422.58050074,
        275887.91147927,  158384.2072171 ,   20958.61570837,
        186094.60049626,  312403.1465091 ,  319917.1124828 ,
        263075.69200633, 1104360.26906748,  252900.07212605,
        275132.25835593,  296685.45574462,  237196.42332498,
       1564742.06113356,  334280.26818206,   56705.66273072,
       1279709.95086077,  199910.29063586,  226798.35011762,
        426699.88634977,  -73732.32344077,  309392.80206873,
        449597.00305942,  203940.19127568,  488424.40205184,
        135769.90468082,  410709.75890595,  196231.97655619,
         88144.05200367,  245082.13985346,  282818.99382725,
        289746.14517236,  221928.31222958,  431232.9235626 ,
        349618.71653502,  623015.27335611,  295508.14597845,
        172373.58066057,  277141.9312721 ,   55652.98602758,
        514832.25893926,  717939.07695252,   97002.9007477 ,
       1133570.67638912,  217101.76301225,  495624.16050351,
         10210.08862284,  400375.70502194,   88434.77174851,
        633379.2932668 ,  423603.72106717,  580228.7616136 ,
        686979.78857151,   39673.6263503 ,  564964.54046965,
        -19316.60483385,   88071.37206746,  281295.97705814,
         77010.65034901,  534600.59305597,  223275.3980213 ,
       1040510.86854209,  256344.92846026,  394571.69555923,
        113626.06252766,   76507.94103149,  527750.85877369,
         23261.76851302,  292279.49879232,  141796.97881561,
        222931.00123926,  603121.75728569,  280705.21322839,
        423603.72106717,  594582.33240858,  466136.82461618,
        353287.78301937, 1892026.16322894,  207317.8546501 ,
        436929.15697166, 1262243.30902228,  263006.48960969,
         57214.4222842 ,  253641.16565906, 1062008.55785975,
       1366983.8200755 ,  553839.87969748,  129658.60183103,
        158384.2072171 , 1114668.62503359,  172813.70020393,
        422531.71824697,  476789.11017068,  542244.47013757,
        279542.334249  ,  262566.93245285,  198026.62803466,
        154777.23638266])

In [36]:
r2_score(y_test,y_pred)

0.6956591542001218

In [37]:
scores=[]
for i in range(1000):
    x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.1,random_state=i)
    lr=LinearRegression()
    pipe=make_pipeline(column_trans,lr)
    pipe.fit(x_train,y_train)
    y_pred=pipe.predict(x_test)
    print(r2_score(y_test,y_pred),i)
    scores.append(r2_score(y_test,y_pred))

0.8107893547501566 0
0.602150091567242 1
0.6967236722769172 2
0.509140372810286 3
0.8781972818550452 4
0.7555611769238578 5
0.43829372678750367 6
0.6341287184802733 7
0.5961754006766498 8
0.732085154431332 9
0.8062689507364611 10
0.7639574601465455 11
0.4922368099278386 12
0.7597816785153615 13
0.7802553918192615 14
0.6872393625709592 15
0.6465432650777501 16
0.7132428364481543 17
0.7371376206693185 18
0.7779783867143923 19
0.7966590563809799 20
0.40314826048985464 21
0.7791565666143454 22
0.7759697856110315 23
0.5784800562799415 24
0.5044959607846327 25
0.7348721529394531 26
0.8324533555572693 27
0.8286313859289947 28
0.611908571619757 29
0.6233936812153573 30
0.8541355169115814 31
0.7150598236943394 32
0.7902635598702921 33
0.8211304310095842 34
0.7959694683639735 35
0.4920462411170894 36
0.710160525778246 37
0.6930511581214363 38
0.8415381828476886 39
0.5222778607856446 40
0.6872911176471455 41
0.5823548740393787 42
0.7033646561578895 43
0.8185978759911983 44
0.7349453895470741 45
0.5906082451378478 46
0.5225743340808717 47
0.8808010418197121 48
0.8577515456725489 49
0.535699304252878 50
0.5929520221219294 51
0.858356519418963 52
0.8402389431149133 53
0.6332558796732496 54
0.7413687288662718 55
0.8732613472993394 56
0.7576461552314239 57
0.7586452899355028 58
0.4463081755819993 59
0.5920025436329337 60
0.5043828204059686 61
0.5623688534692094 62
0.7925765170470875 63
0.7324175529193074 64
0.672399259960367 65
0.4102769791569332 66
0.7448180538548379 67
0.8575786065691119 68
0.7000760806309455 69
0.7929453407287466 70
0.8109474366424555 71
0.6629137216999632 72
0.7225119911832796 73
0.5750424831629363 74
0.830628301237158 75
0.6776662133724898 76
0.7403024691901091 77
0.7139437840756776 78
0.8665413396044794 79
0.5022165975668171 80
0.4796882917837657 81
0.6531317517068762 82
0.8842370072534483 83
0.901660011042331 84
0.664360975200851 85
0.8310390582603919 86
0.7337364159926103 87
0.8437196508490584 88
0.6759570611149768 89
0.7482435866358552 90
0.5012652274212158 91
0.7198430282509143 92
0.6043624815975327 93
0.6802898597145165 94
0.6292747327539947 95
0.6723579446636545 96
0.8370224353614304 97
0.7479960422983615 98
0.6798110843766825 99
0.7977960115809342 100
0.7985133551981972 101
0.7468762864175486 102
0.744422277429709 103
0.642254832260378 104
0.7804127054573646 105
0.5925743076802252 106
0.4695942755976631 107
0.7319367439099582 108
0.8796313581562403 109
0.8654973482607862 110
0.6832602826504852 111
0.6365029153087038 112
0.8263770117397583 113
0.5985720365280973 114
0.5819431883570172 115
0.646623684440814 116
0.6104282606190057 117
0.5182248673206385 118
0.8490823927537338 119
0.8631455483534043 120
0.6136435632799134 121
0.8139128990752249 122
0.7062016120467247 123
0.8637084142575957 124
0.7342820896357527 125
0.782162997615372 126
0.8476374793425445 127
0.5254699895312127 128
0.7620390115123603 129
0.5673988943539843 130
0.685123558662774 131
0.6971969363030415 132
0.7503060698425135 133
0.8809238606725678 134
0.8621899444523325 135
0.5473991127928797 136
0.783907401207515 137
0.6390238615766638 138
0.7792822812570748 139
0.7613768736731207 140
0.5723258434505271 141
0.8091817122209958 142
0.32568026342203493 143
0.8141149688721512 144
0.7919603228105085 145
0.8336187845973542 146
0.6903390689826501 147
0.6863411107397337 148
0.6248251564522125 149
0.6567702570334145 150
0.844606923807999 151
0.6910999990689612 152
0.5631962430352028 153
0.7013046522604904 154
0.7142366612773703 155
0.420373927515134 156
0.8861041208033814 157
0.6732681018899104 158
0.7791848735657618 159
0.6608427632096906 160
0.6255932498493983 161
0.7421571378724529 162
0.5735350804373389 163
0.7238328897883057 164
0.7608080493916773 165
0.8029847324970962 166
0.7437583913588349 167
0.5414595291247318 168
0.7221412855263167 169
0.8098551095157911 170
0.9008104696727768 171
0.8781907646595997 172
0.8004856440061859 173
0.7175445530093911 174
0.5698884269546256 175
0.8220160797784496 176
0.723125730829066 177
0.7232603465051127 178
0.7754795166518971 179
0.75616314719234 180
0.7334587759507796 181
0.6447944818351717 182
0.6973222126896952 183
0.6283608507025046 184
0.8003966232295355 185
0.6464493001945738 186
0.7766304263748662 187
0.7774048487663663 188
0.640257307062745 189
0.8477076454656309 190
0.7304491883551277 191
0.8412875166864101 192
0.7314726100157933 193
0.7984633707626752 194
0.4765717781623856 195
0.07759659119730122 196
0.8420552232489529 197
0.704226401571622 198
0.8226071012443548 199
0.6769617007776327 200
0.7045986879297489 201
0.6112746625000852 202
0.8171723678272311 203
0.6812157908186001 204
0.7701931390419329 205
0.7871058781186044 206
0.620307779029275 207
0.7386072172194984 208
0.6254260610412874 209
0.5663999535073284 210
0.7580002394164349 211
0.6009030772065544 212
0.7859619051753791 213
0.6862737681929832 214
0.7005205085263848 215
0.6644169271990906 216
0.6385562318288617 217
0.8024677535798165 218
0.8722982944801958 219
0.6696845004893595 220
0.7902580774806544 221
0.4851235278696082 222
0.5397575793592204 223
0.5949163599430931 224
0.8058416609955706 225
0.6600615567997996 226
0.7074891095311532 227
0.7342816273869097 228
0.5049660074557527 229
0.7727903996397102 230
0.5916066049598011 231
0.6078707406321293 232
0.6868923878092817 233
0.8104459538941122 234
0.8741738855695605 235
0.84473013791135 236
0.6811036974585272 237
0.5119261501068864 238
0.5661030172789727 239
0.8453017626882844 240
0.32721390008201345 241
0.6880247985303242 242
0.7961088814474283 243
0.6517829498813466 244
0.8123110608251338 245
0.827136717768582 246
0.8883038808664008 247
0.7359433310472093 248
0.16555153177919768 249
0.44697186587505366 250
0.531711706607658 251
0.5362281676590657 252
0.8227667274907042 253
0.713163495100574 254
0.8762889067996207 255
0.6707745994417007 256
0.6889207566165675 257
0.5715120910188043 258
0.4926580719772711 259
0.8645174060396412 260
0.6956067896280773 261
0.8426971416175467 262
0.8158340837338959 263
0.5474471971090594 264
0.5066586492231706 265
0.7221762352542781 266
0.7419599287766516 267
0.85790670545797 268
0.43366378191030186 269
0.6263930232704688 270
0.6072560688115187 271
0.7937928406720027 272
0.6848729152547939 273
0.7555287316755633 274
0.6934261886595985 275
0.7927730534961219 276
0.6783229193360165 277
0.7994485562339327 278
0.8478082527232096 279
0.5887538875828999 280
0.8194945187581348 281
0.7080241620491172 282
0.7626371998915855 283
0.7682522795835968 284
0.6566829352273851 285
0.7324175561840621 286
0.5987655170389602 287
0.716696414576119 288
0.6688368519516288 289
0.6066625210043257 290
0.6504370917785214 291
0.8870674415637513 292
0.7768764686903824 293
0.8681710266690965 294
0.7007572580301917 295
0.7206520977833353 296
0.7992949372366869 297
0.6407404923345039 298
0.850297962288189 299
0.9057140435112662 300
0.8263245178445818 301
0.88594361349925 302
0.6891136856079197 303
0.8111350804637731 304
0.6157703500099775 305
0.8343166164934875 306
0.7312703562493997 307
0.7161721462016881 308
0.8015534579067072 309
0.7930463347480241 310
0.7799365549704602 311
0.3645855820294146 312
0.427733468038651 313
0.4158507217200026 314
0.7550319109638468 315
0.5498377270368071 316
0.6109157593069985 317
0.5677710306932418 318
0.6533387472234924 319
0.5551208544583124 320
0.9120643431032409 321
0.547449645089277 322
0.583713231398499 323
0.6633587732424957 324
0.6911667380328896 325
0.7330445391102272 326
0.6686058967017694 327
0.7015098092794569 328
0.6839324162708913 329
0.6410912551860841 330
0.6955063521642272 331
0.7513004295274681 332
0.6573318199659168 333
0.8266215576010932 334
0.640113053135039 335
0.6197085415385608 336
0.8478890325381508 337
0.8452432318388092 338
0.5234941004099574 339
0.7881688935984126 340
0.7797910260662909 341
0.849001211520231 342
0.7650634944772625 343
0.7247610634099819 344
0.7478852131999052 345
0.6417054892391668 346
0.6007465882727931 347
0.49219766410056676 348
0.6616984554267584 349
0.7283013304775539 350
0.881977147723562 351
0.8834357340062781 352
0.4796826267882929 353
0.6722759426871638 354
0.7565870274285627 355
0.8393223813585187 356
0.7179202275831079 357
0.7609881927226281 358
0.7867925784698052 359
0.6859661734422511 360
0.6466912623298382 361
0.4844266168222675 362
0.7562157071770427 363
0.8446597339307966 364
0.7370274714357564 365
0.9134799725890991 366
0.4269589628113385 367

0.7694356294991762 368
0.8350086721618802 369
0.7386966648724915 370
0.5216321922688785 371
0.4783984490277966 372
0.7867518116842386 373
0.4297566457231733 374
0.7912025063943126 375
0.7417049730070029 376
0.6069730621703476 377
0.891651548888935 378
0.8164204770823308 379
0.5548436499251601 380
0.830198954868034 381
0.8451371979240017 382
0.8562267755112981 383
0.6845527180901625 384
0.7495192841882746 385
0.7739998443546452 386
0.7088721319124223 387
0.5182126648812629 388
0.5632526316862752 389
0.8034208134661744 390
0.7647420667331699 391
0.8560683476624784 392
0.6230051911670493 393
0.6292623041987537 394
0.8033648971276316 395
0.6789600191166171 396
0.6375749467547294 397
0.5384443173792638 398
0.8458812065847809 399
0.714982791480314 400
0.7262964046364526 401
0.6997408280025696 402
0.3884858831316894 403
0.7937995197556319 404
0.4820133644958051 405
0.6432892992233918 406
0.8102975735854209 407
0.824906835274462 408
0.6681856697070188 409
0.8492869099145273 410
0.6845780138566033 411
0.748383874685409 412
0.7177013521907227 413
0.8014636013538506 414
0.7352435818821637 415
0.7258335808651974 416
0.7894771586130461 417
0.755112959789611 418
0.7878195314536642 419
0.7235613735311499 420
0.7009123807627982 421
0.6928960135028908 422
0.6192264782286125 423
0.704768957239209 424
0.5852705785533825 425
0.4489556711888155 426
0.7924932075111166 427
0.7516328592291854 428
0.8210309330942319 429
0.7793139319260132 430
0.8704557272436706 431
0.7536620280066164 432
0.8392788451088391 433
0.4785472028763369 434
0.8463716807451903 435
0.506976192858942 436
0.714498318166314 437
0.623608742832478 438
0.8090833397562398 439
0.904072965974354 440
0.8125082969162702 441
0.8612246419193827 442
0.8574258978209245 443
0.7810731496748893 444
0.7561011126578941 445
0.7183435495465968 446
0.692164803493936 447
0.8045333585376704 448
0.6870297727119901 449
0.6087984314658375 450
0.5892572458808647 451
0.8062399492050911 452
0.7176388213284868 453
0.7351836201936526 454
0.666915491684553 455
0.3927794990523591 456
0.48258804955219015 457
0.7619453877856541 458
0.7462243475963797 459
0.7911760968933231 460
0.5964099622527343 461
0.7137071998086872 462
0.8665867473770954 463
0.43095284176382387 464
0.7409919711249802 465
0.49496519069275746 466
0.703136464916486 467
0.7039139199007555 468
0.739434872389378 469
0.7395968461392769 470
0.42231540875810814 471
0.2356143149177644 472
0.6167324882134698 473
0.7173077397335427 474
0.7342833950153482 475
0.5476639455691503 476
0.876064853220234 477
0.817764011483237 478
0.5672968942181935 479
0.775833145460529 480
0.7777913313274714 481
0.8506931451251898 482
0.7844386476101206 483
0.8415338001260895 484
0.7306809973841888 485
0.7187014370365779 486
0.5593323799366019 487
0.8185026999439587 488
0.6313888964771623 489
0.593657202874657 490
0.7822622511634669 491
0.7809856306041022 492
0.5646428595559334 493
0.777650058044985 494
0.6699937873681152 495
0.7938901979423434 496
0.6669140728454712 497
0.7686559640449058 498
0.8710945077997538 499
0.8468220693799334 500
0.612399762505045 501
0.8545892120737636 502
0.740107824971949 503
0.7032454568400595 504
0.7611277447908006 505
0.629055625066179 506
0.909010538701095 507
0.7428249637278719 508
0.7438526985503391 509
0.7429088529129394 510
0.9131302196277872 511
0.6490958310784092 512
0.7852378693954898 513
0.7162207504574176 514
0.8992105890923421 515
0.7752453408852522 516
0.7744298062333544 517
0.691717378572452 518
0.754228384194969 519
0.7955988979168211 520
0.8108396826291095 521
0.6910919620861107 522
0.5810763240465529 523
0.7766549770647471 524
0.5300476181909077 525
0.8312972869989357 526
0.7816575871995959 527
0.8393823236653695 528
0.5494225344194226 529
0.6895285381928773 530
0.5601405729944288 531
0.5998901262337292 532
0.8452621096662801 533
0.6364205527155158 534
0.7295477407714119 535
0.6750263005742854 536
0.7686908412010014 537
0.6972530302086362 538
0.7398798642155721 539
0.7781584994629374 540
0.6994716429221582 541
0.8466260719074691 542
0.7003358360795995 543
0.7923554516415896 544
0.5237555362391549 545
0.7953600656731795 546
0.5776924525369778 547
0.6601649498709289 548
0.4736575414909916 549
0.6333650868200449 550
0.8327590325550227 551
0.7704765270256586 552
0.8577107335684074 553
0.652784323723026 554
0.8259168956706413 555
0.691571927308951 556
0.6730929104461864 557
0.8391742833275455 558
0.7724719270428106 559
0.65303103509572 560
0.5016341024674957 561
0.7710769629010411 562
0.3624694373494458 563
0.6175547495483537 564
0.7587866971678292 565
0.8321920104910083 566
0.6932901056706369 567
0.7832227801128827 568
0.7018002025784729 569
0.7066904347943312 570
0.6125378972767597 571
0.7722920168326982 572
0.8122615646012034 573
0.8470763027718236 574
0.8099586347636328 575
0.763144671708342 576
0.6399355185901332 577
0.5488691004716979 578
0.5830052349692836 579
0.6034967755423999 580
0.8543704917473138 581
0.41992182418447455 582
0.843339019276972 583
0.41433565157244323 584
0.5263128975661963 585
0.8193513437682032 586
0.8058478182491194 587
0.7916736318945048 588
0.8437645247173251 589
0.8082310193077975 590
0.8123446245653743 591
0.844032555943706 592
0.860243199173829 593
0.7236794792929986 594
0.30484953297264017 595
0.6222383993202106 596
0.3896505895254877 597
0.7654415458914576 598
0.4987878782881888 599
0.4686455375283475 600
0.6648316307249117 601
0.7192665002583929 602
0.7856283282358145 603
0.534147525445739 604
0.7929210364995292 605
0.45721387381446454 606
0.6986150962644107 607
0.8644122828154921 608
0.6502847736829594 609
0.4588389518151539 610
0.5800572506848649 611
0.5558206571742592 612
0.6624665445610866 613
0.843664461386238 614
0.7881345375177679 615
0.6581961449610583 616
0.7642555517384607 617
0.6599669500700143 618
0.5391879248883615 619
0.7128562028064129 620
0.6668086881060835 621
0.5763665137678259 622
0.7801188179190222 623
0.8130107110533249 624
0.721159676275961 625
0.39183242086655956 626
0.6516729721385728 627
0.6456192947834345 628
0.6304678687913088 629
0.6244178611871272 630
0.6176461262010995 631
0.7318132629603151 632
0.6557237171380519 633
0.26597381029000666 634
0.7401967874827986 635
0.842677235426879 636
0.8052325357310841 637
0.8613934412302402 638
0.7988958823070027 639
0.7220189760321509 640
0.7389753531174423 641
0.628989979488553 642
0.790551700006158 643
0.4159662432028688 644
0.7489939136389965 645
0.770974258331029 646
0.7736182790737927 647
0.8038351497731675 648
0.86386312052855 649
0.6202307618561479 650
0.41075947756360665 651
0.9024108068977315 652
0.7905407759999069 653
0.7630145385902138 654
0.920087093218515 655
0.654834573326168 656
0.5270241152326332 657
0.7765449609112978 658
0.7887229491904506 659
0.38957779823915895 660
0.880210346749381 661
0.5458805951371404 662
0.662773459738002 663
0.766415539619344 664
0.6406023180119625 665
0.8425852912381566 666
0.7800550491929635 667
0.7745693364044313 668
0.8346233364462545 669
0.8144638877743429 670
0.6582698448967459 671
0.6301865790312308 672
0.7209041558275624 673
0.7371357026659665 674
0.6938285585243098 675
0.6307758487825816 676
0.5872992026075143 677
0.8454606466955836 678
0.7006128741869829 679
0.7500973965655389 680
0.569344497650356 681
0.731597740491704 682
0.6794543596480649 683
0.5778028150674805 684
0.617264739874432 685
0.843363158779779 686
0.6850474954332798 687
0.6851580170014144 688
0.797966500353636 689
0.6806317495867729 690
0.8171155007759126 691
0.7090133868605247 692
0.6913793927397563 693
0.7241309505309397 694
0.7668565983013395 695
0.7622335044144966 696
0.6158274161703884 697
0.7803561978846468 698
0.7400327391421755 699
0.48658966978074025 700
0.6968992594292642 701
0.5538669172824202 702
0.7464410180357948 703
0.6959373699982191 704
0.6696101679993184 705
0.7450909238295462 706
0.7017145902646871 707
0.5875676855896665 708
0.35866166294146096 709
0.630844071791647 710
0.8341428684340924 711
0.8440451640453444 712
0.8808458847244798 713
0.5890160582005799 714
0.7672646544107493 715
0.8371090038162219 716
0.4241830850844589 717
0.6050927044208294 718
0.6547358593079468 719
0.5125484376914937 720
0.7684555777161214 721
0.7662461228607506 722
0.864358342083779 723
0.6986116724392722 724
0.567619515618562 725
0.6317416953039354 726
0.757853277783026 727
0.6050785946386934 728
0.8701927795482317 729
0.6703823802159303 730

0.719524168771299 731
0.8126090265808514 732
0.6964581518878243 733
0.5657406385609849 734
0.40248051433033827 735
0.7128509390883004 736
0.6498417931694599 737
0.5985053995294999 738
0.5665221830971094 739
0.7631776718244838 740
0.7176072251592525 741
0.7755964726765934 742
0.8430414320905755 743
0.6274719626849294 744
0.6148003026598987 745
0.8012567468298158 746
0.5181757441427194 747
0.5076017560111064 748
0.4718549848516812 749
0.5366745267769015 750
0.7000590456512952 751
0.7309150828950487 752
0.8207849619886929 753
0.8250347750584498 754
0.551962126658221 755
0.7821137618690969 756
0.8197725611473565 757
0.5344777369073386 758
0.5658032091166858 759
0.7495197706415558 760
0.789258966110387 761
0.7971214182079606 762
0.5965884354163897 763
0.6895027592879258 764
0.6170636721374857 765
0.715049109547965 766
0.6902589740253567 767
0.44507560022489523 768
0.8328040349937673 769
0.646025557110347 770
0.6673661588698876 771
0.8257830386765479 772
0.7663069509132698 773
0.557714557709778 774
0.6734352697197774 775
0.5856127874975021 776
0.5817406018351302 777
0.8256668308671195 778
0.6021593318651579 779
0.7823057749698208 780
0.7869657245183749 781
0.7370873407255969 782
0.8489164963390606 783
0.748706013408174 784
0.7923414814025322 785
0.6775767920710409 786
0.6670126691201925 787
0.6591028990900687 788
0.5658463026788241 789
0.8369307761561131 790
0.7622054783469049 791
0.8180559531010154 792
0.8108158749478234 793
0.6901593121919879 794
0.8785060315571876 795
0.8440234695598308 796
0.49393070759246227 797
0.5208999467559821 798
0.643763269183645 799
0.7073765791231399 800
0.45335232795338143 801
0.746976743574427 802
0.6345709092314216 803
0.8353469780982222 804
0.7028797341273145 805
0.6461741195280257 806
0.8573657267623628 807
0.4480923539471243 808
0.7168011767963993 809
0.5096885137392151 810
0.6226868584651706 811
0.7267275283457956 812
0.7014915354529263 813
0.8318750345773126 814
0.59842142789249 815
0.8454141267980027 816
0.8569584697714774 817
0.7709702881151994 818
0.590839205219611 819
0.6937214347345976 820
0.6918166627107106 821
0.7931002121542137 822
0.6786568457007791 823
0.419488932038544 824
0.7263844813145528 825
0.6254724538517837 826
0.7785958423137282 827
0.5365542957138185 828
0.6301586325479058 829
0.4606329422045953 830
0.7991714772817173 831
0.8843304742679772 832
0.5373065921512039 833
0.7912957543794172 834
0.643663323739692 835
0.6789205537543832 836
0.6386535023711342 837
0.6703894347611509 838
0.6958450823660347 839
0.7282975908418049 840
0.8660122669019308 841
0.8096846141242136 842
0.8406677089257684 843
0.6764982862322984 844
0.7526527806780192 845
0.6401632192170328 846
0.7584059672311492 847
0.8207665631702875 848
0.7157279548263522 849
0.7903223615925193 850
0.812908179715492 851
0.7264684131625543 852
0.699494252790329 853
0.7139150669699965 854
0.7554287293213174 855
0.5422689089456401 856
0.4333536444237216 857
0.7728981848046215 858
0.535988212490502 859
0.6730300779658362 860
0.850735919799995 861
0.6622957918074837 862
0.7029281991088214 863
0.6468723634715787 864
0.3148438750818219 865
0.6206665043313353 866
0.7012049294276241 867
0.6169712041180915 868
0.712584164431307 869
0.621685851090807 870
0.5922851629244028 871
0.7833313213529932 872
0.7995585961225425 873
0.8627106692714539 874
0.8141674854850128 875
0.7542166897115461 876
0.7175675217890276 877
0.7685659991591309 878
0.7206341011760208 879
0.830895312345445 880
0.7377046336672606 881
0.6031014923973517 882
0.8808811877837407 883
0.7634046526415812 884
0.6048736843942375 885
0.4421240265837906 886
0.6042110320310601 887
0.8209838154324804 888
0.7311752159718139 889
0.8063766926130675 890
0.7399335260925006 891
0.5293079421378426 892
0.7046816328825611 893
0.7142733845695443 894
0.7601049028885989 895
0.7402324332800032 896
0.6594692261730182 897
0.8013952092301764 898
0.6679593295140174 899
0.902581524436374 900
0.7253461797120522 901
0.4953254774352396 902
0.8927209391536763 903
0.8066288435331537 904
0.8104907296039767 905
0.8851104438710709 906
0.6804686215611718 907
0.759761848745841 908
0.7922107715868907 909
0.8543625994716475 910
0.7110313279261837 911
0.7092687625890262 912
0.5975369863184606 913
0.6235903734777553 914
0.8424220500732487 915
0.4722937677714202 916
0.47837446382201687 917
0.7340870285707173 918
0.446561364598705 919
0.5813858814553508 920
0.8131509316530212 921
0.8119973646213531 922
0.778118749613097 923
0.8322894901636725 924
0.8864662345503237 925
0.8203359800253307 926
0.7320337010428665 927
0.6975038174369879 928
0.599012564499813 929
0.5843027433759367 930
0.8113923104801636 931
0.7213281228330515 932
0.7953586107965062 933
0.7303220598412681 934
0.6602513548825124 935
0.7931467386903142 936
0.7698785483009193 937
0.8411150818374457 938
0.589129300222936 939
0.8472037519590613 940
0.6847787558839105 941
0.7541567427309616 942
0.7206032149105184 943
0.8935169250162774 944
0.7162599149412655 945
0.3930480788354149 946
0.7755456067845552 947
0.6189741892391023 948
0.8318160381558753 949
0.6201708287646985 950
0.706036528232497 951
0.7998343796208791 952
0.7198313829570917 953
0.7983309571232986 954
0.6343654215103608 955
0.7486947223826891 956
0.7785287285185511 957
0.8761790826361229 958
0.7549215306501141 959
0.7634877512716536 960
0.7410544236600132 961
0.5380153132234315 962
0.7736163217060105 963
0.4867515272518782 964
0.8358752665297025 965
0.8893731909588418 966
0.8234816675860586 967
0.8933679776441686 968
0.6900245760866446 969
0.32377556852085043 970
0.6397264911279454 971
0.7485477093026774 972
0.37906449478882687 973
0.8047712444666961 974
0.7310287357452574 975
0.6726015433031532 976
0.7825685153923776 977
0.7117415691389127 978
0.2942309839001823 979
0.6672600076314734 980
0.8658842515602619 981
0.761654855789698 982
0.7285225649832374 983
0.664931414505918 984
0.5925163270804559 985
0.877379848980398 986
0.6749649495071333 987
0.7038629156331362 988
0.7632076440942591 989
0.8284899645429132 990
0.7485189040393856 991
0.6728123446155572 992
0.6661793334751815 993
0.755293925353683 994
0.48518178305305537 995
0.7611800521826824 996
0.7470180789060608 997
0.836815319236732 998
0.786836217127245 999

In [38]:
np.argmax(scores)

655

In [39]:
scores[np.argmax(scores)]

0.920087093218515

## The best model is found at certain random_state

In [40]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.1,random_state=np.argmax(scores))
lr=LinearRegression()
pipe=make_pipeline(column_trans,lr)
pipe.fit(x_train,y_train)
y_pred=pipe.predict(x_test)
r2_score(y_test,y_pred)

0.920087093218515

In [41]:
import pickle

In [42]:
pickle.dump(pipe,open('LinearRegressionModel.pkl','wb'))

In [43]:

pipe.predict(pd.DataFrame(columns=['name','company','year','kms_driven','fuel_type'],data=np.array(['Maruti Suzuki Swift','Maruti',2019,100,'Petrol']).reshape(1,5)))

array([416107.38610967])